### ISSUE TITLE
.env File Exposed

### ISSUE THREAD

**Issue by KikoTs** [DivakovDev/netflix-c#1]
It appears that the `.env` file has been accidentally committed to the repository. This file contains sensitive information such as API keys, database credentials, and other configuration details that should not be publicly accessible.

## Steps to Reproduce

1. Navigate to the repository.
2. Locate the `.env` file in the root directory or other relevant directory.
3. Observe that the file is publicly accessible.

## Impact

The exposure of the `.env` file poses significant security risks, including potential unauthorized access to services and data breaches.

## Immediate Actions Required

1. **Revoke and Regenerate Secrets:** Immediately revoke any secrets (API keys, tokens, passwords) that were exposed and regenerate them as necessary.
2. **Remove the .env File from the Repository:** 
    - Use the following commands to remove the `.env` file from the repository history:
      ```sh
      git rm --cached .env
      echo .env >> .gitignore
      git add .gitignore
      git commit -m "Remove .env file and add to .gitignore"
      git push origin main
      ```
3. **Review Repository History:** Ensure that the `.env` file is not present in any previous commits. You may need to use tools like `BFG Repo-Cleaner` or `git filter-branch` to clean the repository history.
4. **Security Audit:** Conduct a thorough security audit to ensure that no other sensitive information is exposed and that no unauthorized access has occurred.

## Recommendations

1. **Environment Variables:** Store sensitive configuration details in environment variables instead of committing them to the repository.
2. **.gitignore:** Ensure that the `.env` file and other sensitive files are listed in the `.gitignore` file to prevent accidental commits.
3. **Secret Management Tools:** Consider using secret management tools like AWS Secrets Manager, Azure Key Vault, or HashiCorp Vault to securely manage secrets.

Please address this issue as a priority to mitigate any potential security risks.

Thank you.

**Comment by DivakovDev** [comment]
Can you call me when you have a moment?
Because I really want to have a conversation with you. I want to talk and
have real eye to eye contact with someone who knows what I’m talking about!

**Comment by DivakovDev** [comment]
Everything is right I'm done! Thanks for the issue which you send to me!
